#!/bin/bash
# Instrucciones para pushear a GitHub

echo "════════════════════════════════════════════════════════"
echo "  SUBIR CÓDIGO A GITHUB"
echo "════════════════════════════════════════════════════════"
echo ""
echo "OPCIÓN 1: Con gh CLI (más fácil)"
echo "-----------------------------------"
echo "gh repo create nextjs-xss-demo --public --source=. --push"
echo ""
echo "OPCIÓN 2: Manual"
echo "-----------------------------------"
echo "1. Crear repo en GitHub: https://github.com/new"
echo "   Nombre: nextjs-xss-demo"
echo "   Public: ✓"
echo ""
echo "2. Push:"
echo "   git remote add origin https://github.com/jcfavaro/nextjs-xss-demo.git"
echo "   git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════"
